### ISSUE TITLE
portal_inverter_serial should be inverter_serial

### ISSUE THREAD

**Issue by lorrainem77** [hultenvp/solis-sensor#10]
As per the title, configuration.yaml entry should read inverter_serial, not portal_inverter_serial

**Comment by theBOFH** [comment]
cheers @lorrainem77 just ran into this , much appreciated

**Comment by hultenvp** [comment]
Seems to be identical to issue #5. Will be fixed in next release.

**Comment by theBOFH** [comment]
Awesome, cheers @lorrainem77 , oh and special thanks for creating the add-on too

**Comment by hultenvp** [comment]
Thanks!

README is now fixed

Cheers,
Peter
