### ISSUE TITLE
Mixed up sensor values

### ISSUE THREAD

**Issue by Xplode85** [hultenvp/solis-sensor#104]
**Describe the bug**
dc_power_pv3 has the wrong value.
dc_power_pv3 seems to use the value from dc_voltage_pv3 just with the decimal separator moved 1 over.

**Config**
Your anonymized config entry

**Versions**
Integration version: 2.1.0

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/72715336/158209760-56c5f957-b148-456f-8df7-cae9869ffde1.png)
![Screenshot_1](https://user-images.githubusercontent.com/72715336/158209774-5ded6816-f081-4595-bdcc-1444296c73e6.png)
![Screenshot_2](https://user-images.githubusercontent.com/72715336/158209777-ee991bdb-1d7b-4d95-8ee9-bd4d52fc12cc.png)

**Comment by hultenvp** [comment]
I see your point, however if I review the code then the fields I read are the correct ones.
How is the data on ginlong.com? Is the data wrong there as well?

**Comment by Xplode85** [comment]
Thanks for checking.
I checked the website myself and found the problem...but not sure about the cause of the problem.
As you can see here PV3 current is frozen at 0.1A
![Screenshot_4](https://user-images.githubusercontent.com/72715336/158263139-133ac09a-e405-471a-8e94-8d734672dbe4.png)
I found PV3 current has been stuck at 0.1A since the install of the system.
I guess there is some kind of software problem with the inverter.
