### ISSUE TITLE
Yesterday's total energy reported full value next morning, 2 days in row

### ISSUE THREAD

**Issue by kazikskrz** [hultenvp/solis-sensor#106]
I'm having the same here. Every few days I get production value from day before.
version 2.1.0
HA 2022.3.5
![2022-03-28_08h35_43](https://user-images.githubusercontent.com/54333498/160342115-03e4f6e6-674a-4d86-b78d-68f791d445a0.png)
![2022-03-28_08h34_44](https://user-images.githubusercontent.com/54333498/160342133-40c464e7-2024-4614-a6f0-93343d064856.png)
![2022-03-28_08h33_35](https://user-images.githubusercontent.com/54333498/160342142-de9c1b74-67c3-4031-b1a7-06ab49261d2f.png)

_Originally posted by @kazikskrz in https://github.com/hultenvp/solis-sensor/issues/76#issuecomment-1080266134_

**Comment by kazikskrz** [comment]
Hello. Enclosing screenshots
![Energy today 20 min before and after spike](https://user-images.githubusercontent.com/54333498/160996299-ab395eb8-e211-4d27-a7c3-4e280b62730e.png)
![DC Voltage](https://user-images.githubusercontent.com/54333498/160996320-6ebfd811-2220-4ae3-bb26-e75c49b9725a.png)
![DC PV1](https://user-images.githubusercontent.com/54333498/160996335-738f1e99-e29a-4400-a54b-5e9d9bd38a10.png)
![AC Voltage](https://user-images.githubusercontent.com/54333498/160996341-09c34759-5a27-455d-a2b2-4fabe8692cd9.png)
![AC Current](https://user-images.githubusercontent.com/54333498/160996351-be1c347d-d75d-47a5-a6f5-64ae3398d755.png)
![Solis status](https://user-images.githubusercontent.com/54333498/160996368-1b4b74d4-f73d-4f01-8d30-50e842932668.png)

**Comment by hultenvp** [comment]
Thanks @kazikskrz ,
Inverster status is a deprecated sensor (no longer used). Can you add "solis state" screenshot from same period? (see example)
![image](https://user-images.githubusercontent.com/61835400/161049382-d29eb7e4-9341-4d58-bcb4-8d76c1b70556.png)

**Comment by kazikskrz** [comment]
Looks as I did not have this sensor till I have reinstalled integration yesterday. Will paste this State once I get new spike.

**Comment by hultenvp** [comment]
It might be a sign your integration was not entirely up to date, causing the spike. 
Chance is high it's gone now.

**Comment by kazikskrz** [comment]
Seems like reinstalling integration solved this issue. Thank You.
