### ISSUE TITLE
Link to README points to local file

### ISSUE THREAD

**Issue by suneworld** [hultenvp/solis-sensor#109]
When trying to access the docs for the updated config I am linked to a local not-exisiting README file. (See image below).

This is of course not a serious bug but I thought I'd let the developer(s) know :)

![image](https://user-images.githubusercontent.com/74769325/161510058-99e18149-a0c7-42e5-8d85-2e7134245579.png)

**Comment by hultenvp** [comment]
Fixed in https://github.com/hultenvp/solis-sensor/releases/tag/v2.3.1
