### ISSUE TITLE
Local only support

### ISSUE THREAD

**Issue by Shadoweee77** [hultenvp/solis-sensor#110]
Hey,
first of all thank You so much for this!
Would it be possible to make it work local only? Without ever sending data to ginlong. I've stumbled upon this projects: https://github.com/planetmarshall/solis-service and https://github.com/rogersia/Solis-4G It looks to me like it's local. Thanks!

**Comment by hultenvp** [comment]
Hi @Shadoweee77, yes that would be possible, as a matter of fact the other project I took over maintenance for ([Omnik sensor](https://github.com/hultenvp/home_assistant_omnik_solar)) uses that same principle.
But this integration is focusing on fetching data from the cloud. A local only solution would be a different project outside the scope of this integration.
If you're familiar with python, free to fork the omnik project and replace the omnik-specific decoding with solis coding.

**Comment by Shadoweee77** [comment]
Thanks for the reply!
Sadly I have no idea how to use python as of now - learning the general basics atm. Thanks tho!

**Comment by LucidityCrash** [comment]
Something that might be worth looking at for people whom it works :
https://github.com/StephanJoubert/home_assistant_solarman/blob/main/README.md

It appers to talk directy to the datalogger and seems to get quite a log of info out.
My Inverter is RHI-(3-6)K-48ES-5G and my data logger has a serial number starting 408 and a firmware version of MW3_15_0501_1.18

**Comment by hultenvp** [comment]
Closing as won't fix
