### ISSUE TITLE
2 inverters 

### ISSUE THREAD

**Issue by kazikskrz** [hultenvp/solis-sensor#113]
Hi. I have been using your great integration with Solis Ginlog Inverter for quite some time. Good job mate. Now I have added into my house second inventer but this time Sofar. Both report to Solarman platform. It there a way to get second inventer to HA as well?
Thank you for your feedback.

**Comment by hultenvp** [comment]
That shouldn't be any issue. Just add a second config too the configuration.yaml and it should work.

Let me know if it worked out. Cheers.

**Comment by kazikskrz** [comment]
It works perfectly. Thank You so much for your great work.

**Comment by hultenvp** [comment]
Thanks! Glad it works as intended.
