### ISSUE TITLE
ginlong support denied SolisCloud api key

### ISSUE THREAD

**Issue by simbesh** [hultenvp/solis-sensor#120]
Hello, how have others been able to request an API key from ginlong?

Here is their response to my request:
![image](https://user-images.githubusercontent.com/17171925/170412238-f5015449-cb3f-43fd-9266-3469bb2955c5.png)

any help or tips appreciated, thanks.

**Comment by hultenvp** [comment]
Hi, 

Please do not open issues for this, use the [discussion thread](https://github.com/hultenvp/solis-sensor/discussions/71)
The problem you are experiencing is discussed there as well.

Cheers,

**Comment by LucidityCrash** [comment]
Really have to laugh at this ... put "solis api" into Google the first hit is a link to their own support pages ... you'd think they would know this 😁
