### ISSUE TITLE
Battery Charge/Discharge power sensors?

### ISSUE THREAD

**Issue by jasonmadigan** [hultenvp/solis-sensor#129]
**Describe the bug**
Haven't dug into this yet, but I noticed that there are currently no available sensors for battery charge and discharge power. I'm guessing these are available, as I can see them in the portal:

![Screenshot 2022-07-18 at 16 34 22](https://user-images.githubusercontent.com/4467/179548505-88b77f65-a972-46bd-bf1a-a97f15289ac2.png)

**Config**
n/a

**Versions**
Latest HA, Integration version

**Debug logs**
n/a

**Screenshots**

**Comment by jasonmadigan** [comment]
Related PR: https://github.com/hultenvp/solis-sensor/pull/130

**Comment by hultenvp** [comment]
Thanks! Merged them into master.

**Comment by hultenvp** [comment]
Released in v2.3.0
