### ISSUE TITLE
No updates after installing integration

### ISSUE THREAD

**Issue by StoricU** [hultenvp/solis-sensor#137]
I installed the integration using HACS and set it up in the config file.

So far everything seemed to be working great. "All"(a lot) entities where created and the serialnumber of the inverter was showing correct.
However, the entities have never updated.
If I restart HA, all values are unknown for a few minutes, but it is then updated to the same values as before.
![image](https://user-images.githubusercontent.com/50556267/185799751-00113788-a517-4b31-b731-2f63911d9778.png)

yaml input:
![image](https://user-images.githubusercontent.com/50556267/185799821-f7c9724f-8086-47ea-86b0-0932fbf3e7a1.png)

Logging into ginlong.com shoes the correct values:
![image](https://user-images.githubusercontent.com/50556267/185799862-872d256f-9609-4017-a4d8-8103240efd06.png)

Is there some basic config I have forgot?

Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by hultenvp** [comment]
Hi,

The config looks fine and you wouldn't get any sensors if it was wrong. I think the integration crashes on unexpected data. Please check the logs to see if there's an error or warning for Solis. 
If necessary run with debug on:
```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```

**Comment by StoricU** [comment]
Thanks for your quick reply.

I enabled debugging, but that did not give me much.
However I think I figured out the problem.

After I had the system installed, I switched from a wifi to a LAN adapter.
Browsing the solis site now I see that both adapters are registered with the same SN. I don't know why..

However I noticed that the calues in HA is the same as the last values the old adapter registered.
HA:
![image](https://user-images.githubusercontent.com/50556267/185807072-633a7522-d080-489d-b5f3-108940b54307.png)
![image](https://user-images.githubusercontent.com/50556267/185807075-ff4db295-4e02-4728-a256-4a35d7d398ce.png)
Solis:
![image](https://user-images.githubusercontent.com/50556267/185807087-47bbab83-81fc-4646-ad52-c64be3e10a9b.png)


Even though there is a delete button for the adapter, it seems that it doesn't work.
Will contact support and see if they can help me and then see what values that shows up in HA ☺

**Comment by StoricU** [comment]
Correction..
The SN is offcourse the same, since it is the SN of the inverter.
My problem is that there are 2 loggers registered to the device.
The integration automatically fetches the data from the first one, that is not connected any more.

Have sent support a e-mail asking them to delete the old logger. Hopefully that would fix it! :)

**Comment by hultenvp** [comment]
I indeed iterate over the list starting with the newest which is then overwritten by the older one.

If you know how to you can change line 251 in ginlong_api.py from:
```
for record in result_json['result']['paginationAjax']['data']:
```
to
```
for record in reversed(result_json['result']['paginationAjax']['data']):
```

That should fix it and always return the most recent inverter. If it works I'll take this along an an update I'm planning.

**Comment by StoricU** [comment]
Hi,

Thanks for your reply.
However, I was able to delete the logger using the phone app. It was only in the browser the buttons did not work.
So, I'm not able to try the change, sorry.

Will close the issue.
