### ISSUE TITLE
Remove DAILY_ON_GRID_ENERGY

### ISSUE THREAD

**Issue by hultenvp** [hultenvp/solis-sensor#138]
Soliscloud appears to have fixed the bug on the server side.

**Comment by LucidityCrash** [comment]
Hate to say it but not on my api calls ... 
![image](https://user-images.githubusercontent.com/49124523/186447429-2c13fe61-b166-46d3-84d4-fb4f41cb8133.png)

![image](https://user-images.githubusercontent.com/49124523/186447533-17177ef0-381b-49b6-86e9-9aa90d3d0d9f.png)

**Comment by hultenvp** [comment]
Crap, will revert. Planning another fix, will take this along.

Thanks for the heads-up.

**Comment by LucidityCrash** [comment]
> Crap, will revert. Planning another fix, will take this along.
> 
> Thanks for the heads-up. 

Thing that worries me is the guy that did the original pull request to take out the *10 must have done so for a reason.

**Comment by hultenvp** [comment]
True.

@michaelenstone : It looks like what works for you does not work for @LucidityCrash.

I find it difficult to believe you're getting different responses from the same server, but this is Ginlong we're talking about so anything is possible. ;-)

Would you mind running @LucidityCrash's test tool (found [here](https://github.com/hultenvp/solis-sensor/tree/master/test)) and posting the results here?
Let's hope we can find a solution that works for both.

Thanks

**Comment by hultenvp** [comment]
@michaelenstone?

**Comment by michaelenstone** [comment]
Sorry for the delay.  I'm now not getting anything from Solis either in HA or with the tool above (valid login just zero for all values..)

**Comment by michaelenstone** [comment]
Worked it out, I put the wrong id in but still getting nothing for energy today and this month.  Results:

{
    "code": "0",
    "data": {
        "acInType": 0,
        "acOutputType": 0,
        "apparentPower": 520.0,
        "apparentPowerStr": "VA",
        "backupMonthEnergy": 0.0,
        "backupMonthEnergyStr": "kWh",
        "backupTodayEnergy": 0.0,
        "backupTodayEnergyStr": "kWh",
        "backupTotalEnergy": 0.0,
        "backupTotalEnergyStr": "kWh",
        "backupYearEnergy": 0.0,
        "backupYearEnergyStr": "kWh",
        "backupYesterdayEnergy": 0.0,
        "backupYesterdayEnergyStr": "kWh",
        "batteryAcvSet": 0,
        "batteryAlarm": "0",
        "batteryCDEnableSet": 0,
        "batteryCDISet": 0,
        "batteryCDSet": 0,
        "batteryCMaxiSet": 0,
        "batteryCapacitySoc": 100.0,
        "batteryChargeEnergy": 0,
        "batteryChargeEnergyStr": "kWh",
        "batteryChargingCurrent": 0.0,
        "batteryChargingCurrentStr": "A",
        "batteryDMaxiSet": 0,
        "batteryDischargeEnergy": 0,
        "batteryDischargeEnergyStr": "kWh",
        "batteryDischargeLimiting": 50.0,
        "batteryDischargeLimitingStr": "A",
        "batteryFailureInformation01": "0",
        "batteryFailureInformation02": "0",
        "batteryFcvSet": 0,
        "batteryHealthSoh": 100.0,
        "batteryLaTemp": 0.0,
        "batteryMonthChargeEnergy": 0,
        "batteryMonthChargeEnergyStr": "kWh",
        "batteryMonthDischargeEnergy": 0,
        "batteryMonthDischargeEnergyStr": "kWh",
        "batteryOlvEnableSet": 0,
        "batteryOvpSet": 0,
        "batteryPower": 0.153,
        "batteryPowerBms": 0,
        "batteryPowerBmsStr": "kW",
        "batteryPowerFu": 0,
        "batteryPowerPec": "1",
        "batteryPowerStr": "kW",
        "batteryPowerZheng": 153.0,
        "batteryTodayChargeEnergy": 0.0,
        "batteryTodayChargeEnergyStr": "kWh",
        "batteryTodayDischargeEnergy": 0.0,
        "batteryTodayDischargeEnergyStr": "kWh",
        "batteryTotalChargeEnergy": 171.0,
        "batteryTotalChargeEnergyStr": "kWh",
        "batteryTotalDischargeEnergy": 233.0,
        "batteryTotalDischargeEnergyStr": "kWh",
        "batteryType": "1",
        "batteryUvpSet": 0,
        "batteryVoltage": 50.52,
        "batteryVoltageStr": "V",
        "batteryYearChargeEnergy": 0,
        "batteryYearChargeEnergyStr": "kWh",
        "batteryYearDischargeEnergy": 0,
        "batteryYearDischargeEnergyStr": "kWh",
        "batteryYesterdayChargeEnergy": 5.1,
        "batteryYesterdayChargeEnergyStr": "kWh",
        "batteryYesterdayDischargeEnergy": 5.0,
        "batteryYesterdayDischargeEnergyStr": "kWh",
        "bstteryCurrent": 0.6,
        "bstteryCurrentStr": "A",
        "bypassAcCurrent": 3.0,
        "bypassAcCurrentB": 0,
        "bypassAcCurrentC": 0,
        "bypassAcCurrentSet": 0,
        "bypassAcOnoffSet": 0,
        "bypassAcVoltage": 236.7,
        "bypassAcVoltageB": 0,
        "bypassAcVoltageC": 0,
        "bypassAcVoltageSet": 0,
        "bypassLoadPower": 0.0,
        "bypassLoadPowerStr": "kW",
        "collectorId": "",
        "collectorsn": "",
        "currentState": "3",
        "dataTimestamp": "1661529402738",
        "daylight": 0,
        "dcBus": 389.6,
        "dcBusHalf": 0.0,
        "dcBusHalfStr": "V",
        "dcBusStr": "V",
        "dcInputtype": 1,
        "dispersionRate": 0.0,
        "eMonth": 499.0,
        "eMonthStr": "kWh",
        "eToday": 18.2,
        "eTodayStr": "kWh",
        "eTotal": 680.0,
        "eTotalStr": "kWh",
        "eYear": 680.0,
        "eYearStr": "kWh",
        "epmFailSafe": 0,
        "epmSafe": 0,
        "epsDDepth": 0,
        "epsSwitchTime": "0",
        "fac": 49.94,
        "facStr": "Hz",
        "familyLoadPercent": 0,
        "familyLoadPower": 0.18,
        "familyLoadPowerPec": "1",
        "familyLoadPowerStr": "kW",
        "fullHour": 0.0,
        "fullHourStr": "h",
        "gridPurchasedEnergy": 0,
        "gridPurchasedEnergyStr": "kWh",
        "gridPurchasedMonthEnergy": 0,
        "gridPurchasedMonthEnergyStr": "kWh",
        "gridPurchasedTodayEnergy": 0.0,
        "gridPurchasedTodayEnergyStr": "kWh",
        "gridPurchasedTotalEnergy": 69.0,
        "gridPurchasedTotalEnergyStr": "kWh",
        "gridPurchasedYearEnergy": 0,
        "gridPurchasedYearEnergyStr": "kWh",
        "gridPurchasedYesterdayEnergy": 3.6,
        "gridPurchasedYesterdayEnergyStr": "kWh",
        "gridSellEnergy": 0,
        "gridSellEnergyStr": "kWh",
        "gridSellMonthEnergy": 0,
        "gridSellMonthEnergyStr": "kWh",
        "gridSellTodayEnergy": 0.0,
        "gridSellTodayEnergyStr": "kWh",
        "gridSellTotalEnergy": 314.0,
        "gridSellTotalEnergyStr": "kWh",
        "gridSellYearEnergy": 0,
        "gridSellYearEnergyStr": "kWh",
        "gridSellYesterdayEnergy": 8.6,
        "gridSellYesterdayEnergyStr": "kWh",
        "homeGridMonthEnergy": 0.0,
        "homeGridMonthEnergyStr": "kWh",
        "homeGridTodayEnergy": 0.0,
        "homeGridTodayEnergyStr": "kWh",
        "homeGridTotalEnergy": 0.0,
        "homeGridTotalEnergyStr": "kWh",
        "homeGridYearEnergy": 0.0,
        "homeGridYearEnergyStr": "kWh",
        "homeGridYesterdayEnergy": 0.0,
        "homeGridYesterdayEnergyStr": "kWh",
        "homeLoadEnergy": 0,
        "homeLoadEnergyStr": "kWh",
        "homeLoadTodayEnergy": 0.0,
        "homeLoadTodayEnergyStr": "kWh",
        "homeLoadTotalEnergy": 492.0,
        "homeLoadTotalEnergyStr": "kWh",
        "homeLoadYesterdayEnergy": 13.1,
        "homeLoadYesterdayEnergyStr": "kWh",
        "iAc1": 3.0,
        "iAc1Str": "A",
        "iAc2": 0.0,
        "iAc2Str": "A",
        "iAc3": 0.0,
        "iAc3Str": "A",
        "iLeakLimt": 0,
        "iPv1": 1.3,
        "iPv1Str": "A",
        "iPv2": 1.1,
        "iPv2Str": "A",
        "id": "1308675217947271901",
        "insulationResistance": 0,
        "inverterMeterModel": 5,
        "inverterTemperature": 38.3,
        "inverterTemperatureUnit": "\u2103",
        "ipvTotal": 0,
        "ipvTotalStr": "A",
        "model": "3104",
        "nationalStandardstr": "G99",
        "offGridDDepth": 0,
        "oneSelf": 79.0,
        "pac": 0.556,
        "pacPec": "1",
        "pacStr": "kW",
        "parallelAddr": 0,
        "parallelBattery": 0,
        "parallelPhase": 0,
        "parallelStatus": 0,
        "pepm": 0.0,
        "pepmSet": 0.0,
        "pepmSetStr": "kW",
        "pepmStr": "kW",
        "porwerPercent": 0.111,
        "pow1": 391,
        "pow1Str": "W",
        "pow2": 165,
        "pow2Str": "W",
        "powTotal": 0,
        "powTotalStr": "W",
        "power": 5.0,
        "powerFactor": 0.0,
        "powerPec": "1",
        "powerStr": "kWp",
        "productModel": "3104",
        "psum": 0.324,
        "psumCal": 0.324,
        "psumCalPec": "1",
        "psumCalStr": "kW",
        "psumStr": "kW",
        "reactivePower": 0.0,
        "reactivePowerStr": "Var",
        "rs485ComAddr": "101",
        "simFlowState": -1,
        "sirRealtime": 0,
        "sn": "",
        "sno": "",
        "socChargingSet": 15,
        "socDischargeSet": 20,
        "state": 1,
        "stateExceptionFlag": 0,
        "stationId": "",
        "storageBatteryCurrent": -3.0,
        "storageBatteryCurrentStr": "A",
        "storageBatteryVoltage": 51.0,
        "storageBatteryVoltageStr": "V",
        "tag": "zhichuan",
        "temp": 105.0,
        "tempName": "inverter internal operating ambient temperature",
        "timeStr": "2022-08-26 15:56:42",
        "timeZone": 0.0,
        "totalLoadPower": 0,
        "totalLoadPowerStr": "kW",
        "uAc1": 236.6,
        "uAc1Str": "V",
        "uAc2": 0.0,
        "uAc2Str": "V",
        "uAc3": 0.0,
        "uAc3Str": "V",
        "uInitGnd": 0,
        "uInitGndStr": "V",
        "uPv1": 301.0,
        "uPv1Str": "V",
        "uPv2": 150.1,
        "upvTotal": 0,
        "upvTotalStr": "V",
        "userId": "",
        "version": "3C0032",
        "warningInfoData": 0
    },
    "msg": "success",
    "success": true
}

**Comment by hultenvp** [comment]
There are indeed some inconsistencies.

"gridSellEnergy": 0,
"gridSellEnergyStr": "kWh",
"gridSellMonthEnergy": 0,
"gridSellMonthEnergyStr": "kWh",
"gridSellTodayEnergy": 0.0,
"gridSellTodayEnergyStr": "kWh",
"gridSellTotalEnergy": 314.0,
"gridSellTotalEnergyStr": "kWh",
"gridSellYearEnergy": 0,
"gridSellYearEnergyStr": "kWh",
"gridSellYesterdayEnergy": 8.6,
"gridSellYesterdayEnergyStr": "kWh",

It could be possible you did not sell energy today, but you sold yesterday, so the year figure can never be right.
But did you see figures on daily grid sell energy that were correct and did not require any *10 correction?

**Comment by michaelenstone** [comment]
I had the correct figures for about 2 weeks, basically since I posted the
pull request. One day the grid sell energy was 10x bigger than the day
before. So I looked at your code, made the change and pushed it through.

I stopped getting data on the 24th in the afternoon.

I've now updated to the latest version and I'm getting some data but it's
inconsistent...

**Comment by hultenvp** [comment]
I don't see how the changes in my update could have contributed and the output of the test script also indicates the issue is server side.
SolisCloud is still work in progress and this kind of confusing behaviour has been observed before. I can only assume their devops processes are not really state of the art yet.
If you want a stable experience I recommend you go to m.ginlong.com and make that account your primary (you can run them in parallel) until SolisCloud stabilizes. 

I'm going to see if I can make a yaml file to switch workarounds on/off. If not, then I propose I revert the change for now.

Thanks for your help.
Cheers
