### ISSUE TITLE
SolisCloud Invalid Credentials

### ISSUE THREAD

**Issue by alienatedsec** [hultenvp/solis-sensor#173]
My integration worked perfectly fine before moving from 2.x.x to 3.0.2 shortly before opening this issue.

Whenever trying to use existing API credentials (not new, existing that was working via configuration.yaml) I have the below error appearing

![image](https://user-images.githubusercontent.com/73167064/197355316-8013bd6e-de4d-4d4c-bd20-e2a9abf9862c.png)

How to troubleshoot or what could be wrong with the URL or credentials?

**Comment by alienatedsec** [comment]
@hultenvp I reverted to 2.3.5, and it is working fine again.

![image](https://user-images.githubusercontent.com/73167064/197356950-fc2f0d6f-06cd-4696-bb4d-6c94822a2912.png)

**Comment by hultenvp** [comment]
The has been some discussion on the discussions page. The plant_id is handled as an int, but for some values it starts rounding the int for some reason I still do not entirely get. In the configuration.yaml the plant_id is handled as a string.

**Comment by hultenvp** [comment]
Can't fully validate myself, but should work now

**Comment by alienatedsec** [comment]
@hultenvp Again the same problem with the recent version
