### ISSUE TITLE
error with batcapacityremaining, battotalenergycharged & battotalenergydischarged 

### ISSUE THREAD

**Issue by RCGrahamWilmott** [hultenvp/solis-sensor#19]
I can't seem to put batcapacityremaining, battotalenergycharged or battotalenergydischarged into my configuration.yaml file.

When I add these lines, I get the following errors:
`Invalid config for [sensor.solis]: sensor batcapacityremaining does not exist. Got OrderedDict([('platform', 'solis'), ('name', 'Solar'), ('portal_domain', 'm.ginlong.com'), ('portal_username', 'XXXXXXXX'), ('portal_password', 'XXXXXXXX'), ('portal_plant_id', '1397598'), ('inverter_serial', '160F52218120075'), ('sensors', OrderedDict([('actualpower', None), ('energytoday', None), ('status', None), ('temperature', None), ('dcinputvoltagepv1', None), ('dcinputvoltagepv2', None), ('dcinputcurrentpv1', None), ('dcinputcurrentpv2', None), ('acoutputvoltage1.... (See ?, line ?).`

`Invalid config for [sensor.solis]: sensor battotalenergycharged does not exist. Got OrderedDict([('platform', 'solis'), ('name', 'Solar'), ('portal_domain', 'm.ginlong.com'), ('portal_username', 'XXXXXXXX'), ('portal_password', 'XXXXXXXX'), ('portal_plant_id', '1397598'), ('inverter_serial', '160F52218120075'), ('sensors', OrderedDict([('actualpower', None), ('energytoday', None), ('status', None), ('temperature', None), ('dcinputvoltagepv1', None), ('dcinputvoltagepv2', None), ('dcinputcurrentpv1', None), ('dcinputcurrentpv2', None), ('acoutputvoltage1.... (See ?, line ?).`

`Invalid config for [sensor.solis]: sensor battotalenergydischarged does not exist. Got OrderedDict([('platform', 'solis'), ('name', 'Solar'), ('portal_domain', 'm.ginlong.com'), ('portal_username', 'XXXXXXXX'), ('portal_password', 'XXXXXXXX'), ('portal_plant_id', '1397598'), ('inverter_serial', '160F52218120075'), ('sensors', OrderedDict([('actualpower', None), ('energytoday', None), ('status', None), ('temperature', None), ('dcinputvoltagepv1', None), ('dcinputvoltagepv2', None), ('dcinputcurrentpv1', None), ('dcinputcurrentpv2', None), ('acoutputvoltage1.... (See ?, line ?).`

Everything else is working correctly. Happy to provide logs / try to help debug

## System Health

version | core-2021.10.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4927
Installed Version | 1.15.2
Stage | running
Available Repositories | 895
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.0
docker_version | 20.10.7
disk_total | 57.8 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.11.0), File editor (5.3.3), Home Assistant Google Drive Backup (0.105.2), SQLite Web (3.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 3
views | 9
mode | storage

</details>

**Comment by hultenvp** [comment]
Hi @RCGrahamWilmott,

My hunch would be that one or more files are not latest. Please double check you have latest files.
platform2_portal must be v0.0.5, sensor.py must be v0.2.2. Const.py has no version, but the dict is declared there, so ensure that const.py contains (see last 3 lines):
```
SENSOR_TYPES = {
    'status':                   ['Status', None, 'mdi:solar-power', None, None],
    'temperature':              ['Temperature', TEMP_CELSIUS, 'mdi:thermometer', DEVICE_CLASS_TEMPERATURE, STATE_CLASS_MEASUREMENT],
    'dcinputvoltagepv1':        ['DC Voltage PV1', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'dcinputvoltagepv2':        ['DC Voltage PV2', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'dcinputvoltagepv3':        ['DC Voltage PV3', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'dcinputvoltagepv4':        ['DC Voltage PV4', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'dcinputcurrentpv1':        ['DC Current PV1', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'dcinputcurrentpv2':        ['DC Current PV2', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'dcinputcurrentpv3':        ['DC Current PV3', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'dcinputcurrentpv4':        ['DC Current PV4', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'acoutputvoltage1':         ['AC Voltage R', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'acoutputvoltage2':         ['AC Voltage S', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'acoutputvoltage3':         ['AC Voltage T', 'V', 'mdi:flash-outline', DEVICE_CLASS_VOLTAGE, STATE_CLASS_MEASUREMENT],
    'acoutputcurrent1':         ['AC Current R', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'acoutputcurrent2':         ['AC Current S', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'acoutputcurrent3':         ['AC Current T', 'A', 'mdi:flash-outline', DEVICE_CLASS_CURRENT, STATE_CLASS_MEASUREMENT],
    'actualpower':              ['AC Output Total Power', 'W', 'mdi:weather-sunny', DEVICE_CLASS_POWER, STATE_CLASS_MEASUREMENT], 
    'energylastmonth':          ['Energy Last Month', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'energytoday':              ['Energy Today', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'energythismonth':          ['Energy This Month', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'energythisyear':           ['energy This Year', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'energytotal':              ['Energy Total', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'batcapacityremaining':     ['Remaining battery capacity', '%', 'mdi:battery', DEVICE_CLASS_BATTERY, STATE_CLASS_MEASUREMENT],
    'battotalenergycharged':    ['Total Energy Charged', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
    'battotalenergydischarged': ['Total Energy Discharged', 'kWh', 'mdi:flash-outline', DEVICE_CLASS_ENERGY, STATE_CLASS_TOTAL_INCREASING],
}
```
