### ISSUE TITLE
cant access configuration via UI

### ISSUE THREAD

**Issue by kraexx** [hultenvp/solis-sensor#208]
Hi!

i have installed this via HACS, and checked the custom_components dir, and all seems fine.
i cannot however find the configuration "portal selection" anywhere?
please help

**Comment by hultenvp** [comment]
Please use discussion for this. Do not create bugs for support.

Go to settings->devices and services. Add integration, select Solis and you'll get a menu as shown in the readme.

If you need more help, please open a discussion.

Cheers
