### ISSUE TITLE
Solis Inverter Energy Today starts the day with an erroneous offset

### ISSUE THREAD

**Issue by GillesC** [hultenvp/solis-sensor#212]
**Describe the bug**
As can be seen from the screenshot, the `Solis Inverter Energy Today` entity always outputs a wrong energy production value at the start of the day (after booting up). The issue seems somewhat related to #128. 

**Config**
N.A.

**Versions**
Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

m.ginlong.com integration

**Screenshots**
![image](https://user-images.githubusercontent.com/8626571/202894910-b3183b38-3991-4cee-baeb-eaf2b82b639d.png)

**Comment by hultenvp** [comment]
Yes, the ginlong API only resets energy today in the morning when the device comes back online.
The general rule I apply to filter this out is: If it's AM and the inverter is offline return "0".
If it's AM and the inverter is online then return the actual value. If it's PM, return actual value.

What I see in the screenshot is that indeed "0" is returned as long as the sun is not up. But it looks like the inverter merrily continues adding to the energy today of the previous day after it comes back online until _exactly_ 12 o'clock. 
I suspect your time or timezone settings are wrong. I'd check configuration of both the portal and your inverter, but my guess is the inverter is incorrectly configured because of an AM/PM misconfiguration

**Comment by PieterVandenBerge** [comment]
So do you create a new entity then to make this work (resetting daily
solar)?
Sorry about the noob question but would be great if you could share the
code for this.
Thanks!

**Comment by PieterVandenBerge** [comment]
![image](https://user-images.githubusercontent.com/47532422/204757031-419b3e31-a19d-4594-8248-36514629babf.png)
I do see the same happening on SOLIS cloud as well. It seems they don't reset immediately at start-up after begin OFF during the night..

![image](https://user-images.githubusercontent.com/47532422/204757193-4bbae22e-e7e8-4cf3-a470-99de3c3619c7.png)
If the battery is powered on, the issue isn't happening.
(My battery is currently switched off as it's charging from the net which is very undesired behavior and that is something that SOLIS is also currently investigating (at least according to my installer)).

**Comment by hultenvp** [comment]
> So do you create a new entity then to make this work (resetting daily solar)? Sorry about the noob question but would be great if you could share the code for this. Thanks!

Nope, I simply filter the Energy today data received from the server before updating the sensor entity.
The filtering code can be found here: 
https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/service.py#L153-L176

**Comment by hultenvp** [comment]
> ![image](https://user-images.githubusercontent.com/47532422/204757905-2c719256-b200-4db7-af98-fafb232c37e8.png) I do see the same happening on SOLIS cloud as well. It seems they don't reset immediately at start-up after begin OFF during the night..
> 
> ![image](https://user-images.githubusercontent.com/47532422/204757193-4bbae22e-e7e8-4cf3-a470-99de3c3619c7.png) If the battery is powered on, the issue isn't happening. (My battery is currently switched off as it's charging from the net which is very undesired behavior and that is something that SOLIS is also currently investigating (at least according to my installer)).

Correct. That's why I filter, in the code you also see a 5 min grace period to avoid still catching the final measurement from previous day. 
Behaviour with battery on is different because the battery typically keeps the inverter on past midnight.

**Comment by GillesC** [comment]
> > So do you create a new entity then to make this work (resetting daily solar)? Sorry about the noob question but would be great if you could share the code for this. Thanks!
> 
> Nope, I simply filter the Energy today data received from the server before updating the sensor entity. The filtering code can be found here: https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/service.py#L153-L176

So, as it is already implemented, I'll have to check the timezone to resolve the issue I am seeing now?

**Comment by GillesC** [comment]
> Yes, check time and locale settings both on the server and in your inverter. I've seen both scenarios.

Both are filled in correctly. I have checked the HA host and the soliscloud show the same wall clock as expected.

**Comment by hultenvp** [comment]
Did you also check the timezone? It can't be coincidence your server data resets at 12 noon instead of 12 midnight.

**Comment by GillesC** [comment]
> Did you also check the timezone? It can't be coincidence your server data resets at 12 noon instead of 12 midnight.

Hi, yes, both are set to UTC + 1. It is indeed weird....

At solis Cloud:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/8626571/206453495-eef0e88a-27ab-40ed-b362-e29779ae611a.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/8626571/206453736-0a27c728-e20a-467a-b178-8f4a9d729cef.png">

At HA:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/8626571/206453791-887e0296-d7aa-43e6-8a71-b82d129af5b7.png">

Any pointers, where to look?

**Comment by GillesC** [comment]
I have maybe a bold suggestion. Could we do the following:
- if first value of the day of `INVERTER_ENERGY_TODAY`,  `initial_value=value`
-` value = value - initial_value`, as long as the day is not pasted (or till inverter goes offline)
- if `value` is below previous value (or 0?) and the inverter has not gone offline in the mean time,  `initial_value=value`

**Comment by GillesC** [comment]
I was unaware that the timing shown on the soliscloud did not reflect the time used by the inverter.
The inverter time was indeed 12h off.

**For other having this problem: check the manual of your inverter to see how to adjust the time and time zone.**

Thank you for your patience @hultenvp!

**Comment by hultenvp** [comment]
Good to see it's solved! I indeed wanted to ask you to also double check the inverter itself.

**Comment by PieterVandenBerge** [comment]
I looked into the manual to see how I could change the time zone on my inverter:
![image](https://user-images.githubusercontent.com/47532422/206668852-40f9ff62-def1-4573-b256-359123ded0eb.png)
However, there's only mention of time. Not timezone.

When I check then the datalogger on soliscloud:
![image](https://user-images.githubusercontent.com/47532422/206669646-4cda2efc-7b59-4c38-aacb-5255391f6f54.png)
It has the same timezone (I'm on Brussels' time).

So not really sure what I still need to change...
