### ISSUE TITLE
Solis Energy Today entity became unavailable

### ISSUE THREAD

**Issue by PieterVandenBerge** [hultenvp/solis-sensor#216]
**Describe the bug**
Solis Energy Today entity became unavailable. I was using this to track how much kWh is generated on the panels.
![image](https://user-images.githubusercontent.com/47532422/203580775-770640ad-f4e6-4fb0-a693-ca36ed809d39.png)

Which leads to
![image](https://user-images.githubusercontent.com/47532422/203581028-b7727a41-145e-4807-ac38-732de95b10d7.png)

It seems to have started yesterday 22nd of November
![image](https://user-images.githubusercontent.com/47532422/203581217-48c6e671-1035-4f08-8703-3ea0af708424.png)

**Versions**
Home Assistant Core Installed version 2022.11.2
Solis integration v3.1.0

***NEXT***
I tried updating HA Core but this seems to have made it worse only:
Home Assistant 2022.11.4
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

Now all entities seem to have become unavailable.
![image](https://user-images.githubusercontent.com/47532422/203583803-88c835b2-7b58-44e1-bfbe-8c1f52547361.png)

Let me know if any additional info would be required.

**Comment by PieterVandenBerge** [comment]
I reverted back to Home Assistant Core 2022.11.2 and now all entities are available again including Solis Energy Today.
However, I'm now not convinced I should update HA Core. 

Looking forward to any feedback.

**Comment by hultenvp** [comment]
I'm on 2022.11.3. No problems there. Will update now and see if I can reproduce your issue.

**Comment by hultenvp** [comment]
My upgrade was flawless, all works fine. 
I'll need a debug log to investigate.

**Comment by Chris370-arch** [comment]
Had this same issue (2022.11.4), performed a reload and it stopped working. A restart of the integration did not resolve. I had to perform a proper power cycle of HA.

**Comment by hultenvp** [comment]
Maybe related to the timeout discussed in #183

**Comment by hultenvp** [comment]
I'll close this issue, further issues after release 3.2.0 please report in #232
