### ISSUE TITLE
battotalenergycharged & battotalenergydischarged only showing full kWh

### ISSUE THREAD

**Issue by RCGrahamWilmott** [hultenvp/solis-sensor#23]
Both battotalenergycharged and battotalenergydischarged are only returning full kWh on the energy dashboard, rather than showing in W or fractions of kWh. This leads to strange spikes in the graph:
![image](https://user-images.githubusercontent.com/4955769/138589817-c691c202-f1ca-4d5c-8599-d82ee0c9458f.png)

The https://m.ginlong.com/ website shows battery charge/discharge in W. I think it might be a datatype issue (integer rather than float?) but not 100% sure.

**Comment by hultenvp** [comment]
One question to verify I understand what the values mean, so I can improve the descriptions a bit. I particular the first one seems a bit ambiguous for non-native English speakers:
Daily On-grid Energy: Energy given back to grid
Daily Energy Purchased: Energy taken from grid
Daily Energy Used: Total energy consumed by the household

Cheers

**Comment by RCGrahamWilmott** [comment]
I've been using the current version and it seems to be working perfectly. (I've checked the data matches the data on the website, which as expected it does).

sensor.solar_daily_grid_energy_used - seems to be the total amount of energy that has gone from the invertor (solar or battery) to the house. I think "total energy used by the house" would be a good summary.

sensor.solar_daily_grid_energy_purchased - This seems to be the amount of energy I purchased yesterday. (It isn't matching the amount of energy I am using today, but does match (but rounded down) to what I used yesterday). I am going to keep an eye on this...

sensor.solar_daily_on_grid_energy - I'm not currently exporting so can't check this. (Unless we get a very sunny day, I might not export much until the spring). However, I believe this to be the energy given back / sold to the grid. I think it would be great to rename this. I might see if I can "force" myself to export something and triple-check this is all working, but I am seeing zero in HA (as expected), and this was the correct variable on the https://m.ginlong.com/ website when I was able to export a bit.

Also, every icon in home assistant is the standard electricity icon. Prehaps some could be something like mdiHomeImportOutline / mdiHomeExportOutline / mdiTransmissionTowerImport / mdiTransmissionTowerExport / mdiBatteryPlus / mdiBatteryArrowUp / mdiBatteryMinus / mdiBatteryArrowDown to help make it clear what each sensor does?

**Comment by RCGrahamWilmott** [comment]
(Typo on line 366 of "/config/custom_components/solis/platform2_portal.py" - GRID_DTOTAL_POWER should be GRID_TOTAL_POWER )

**Comment by hultenvp** [comment]
Hi @RCGrahamWilmott ,

Thanks for the clarification. I have updated the readme a bit, we can change it further if you have progressing insights.
I've also updated the icons following your suggestions. If you want to improve them further then feel free to make a pull request.

Typo fixed!

**Comment by hultenvp** [comment]
Hi @RCGrahamWilmott ,

I saw you reviewed my PR to get integrated into HACS. Didn't know you were involved in HACS, thanks for reviewing.
Do you have any insight when the others will review? Is that an ad-hoc process or do they review and integrate periodically?

If unclear, do you know if I can continue to release on my project or does that interfere with the HACs integration PR? I assume there are no dependencies, but I'd like to be sure ;-)

TIA,
Peter

**Comment by hultenvp** [comment]
Merged and release in v0.3.3. No default repo in HACS yet
