### ISSUE TITLE
solis_battery_power is always positive value

### ISSUE THREAD

**Issue by matthewbyrne** [hultenvp/solis-sensor#256]
**Describe the bug**
Up until this week the `solis_battery_power` entity was negative while discharging, and positive while charging. Now it seems as though it is always positive.

**Versions**
HA Version an deployment 2022.12.7
HACS version 1.30.1
Integration version v3.3.1

**Screenshots**
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/20643528/216582784-983ef48f-dcdf-400b-ac9d-d2a01848318f.png">

**Comment by matthewbyrne** [comment]
Feels like this change broke it
https://github.com/hultenvp/solis-sensor/pull/250

**Comment by hultenvp** [comment]
Can you perhaps make a screenshot with both battery power and battery current?

**Comment by matthewbyrne** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/20643528/218303382-137dcc99-00bb-4d21-84dc-abac96c7097a.png">

From ~6am today was me charging the battery, and from 8am was me using the battery. As you can see, both are positive.
<img width="542" alt="image" src="https://user-images.githubusercontent.com/20643528/218303392-6afc8b3a-b061-4cc8-93af-23440abc51de.png">

**Comment by matthewbyrne** [comment]
Correct. Soliscloud. 

I've had to resort to @barthoefs fix from here:
https://github.com/hultenvp/solis-sensor/issues/249#issuecomment-1379991258

**Comment by hultenvp** [comment]
Ughh, you are right, there is a mistake in the code. 🤦 
```
            # turn batteryPower negative when discharging (fix for https://github.com/hultenvp/solis-sensor/issues/158)
            try:
                math.copysign(self._data[BAT_POWER],self._data[BAT_CURRENT])
            except KeyError:
                pass
```
should be:
```
            # turn batteryPower negative when discharging (fix for https://github.com/hultenvp/solis-sensor/issues/158)
            try:
                self._data[BAT_POWER] = math.copysign(self._data[BAT_POWER],self._data[BAT_CURRENT])
            except KeyError:
                pass
```
