### ISSUE TITLE
Multiple inverters on Station showing as a single Device

### ISSUE THREAD

**Issue by swests** [hultenvp/solis-sensor#285]
**Describe the bug**
My setup has two inverters, one hybrid and one to grid.  I successfully added the plant and see 1 device. I was expecting the entities to be shown per inverter (Device).  If I run the test scripts I see you're extracting each logger and inverter for the station.  Is this a bug in the integration or as intended - for all entities to show under a single device?

**Config**
GUI Setup for SolisCloud

**Versions**
HA Version an deployment - HA 2023.4.6, HAOS running as VM
HACS version - 1.32.1
Integration version - v3.3.2

**Debug logs**
Add to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
And attach the resulting log to the issue. If yo do not know where to find logs you missed an important step in the install of HACS. ;-)

**Screenshots**
![image](https://github.com/hultenvp/solis-sensor/assets/5365747/23b27680-e6de-4d40-a007-1e153eeabafc)
![image](https://github.com/hultenvp/solis-sensor/assets/5365747/937c4ecc-cb61-40a4-be95-bc3d86bc70d0)

**Comment by swests** [comment]
@hultenvp  - would you please comment on this.  Many thanks.

**Comment by hultenvp** [comment]
Hi, renovating the house, so had no time to work on this project so far. Even didn't have the panels on the roof for a while ;-)

This is probably a bug. Intent is to show each individual inverter as a device under the station.
I do not see any issue in my code that could cause this. Can you add debug output here? Please follow the instructions in the wiki if you don't know how to do it.

**Comment by swests** [comment]
Hi.

Good luck with the renovations - I remember that experience.

For debug, I guess you'd like me to remove the integration, and then re-add as I guess the issue is somewhere during the initial setup.  Please confirm.

 Is there a chance that there are some stale artefacts that could do with deletion? And if so how would I find them.

**Comment by hultenvp** [comment]
Let's first start with switching debug on and then reloading the integration. It should give me some initial data. Would be great if you could provide me with that info.
Based on that I might have to make a custom version to get more targeted debug output.

**Comment by hultenvp** [comment]
I can (finally) reproduce the issue, no solution yet

**Comment by hultenvp** [comment]
Fixed
