### ISSUE TITLE
Can no longer get data or create new integration with Solis login

### ISSUE THREAD

**Issue by usbrit** [hultenvp/solis-sensor#299]
**Describe the bug**
About a month ago I lost all sensor data from the integration. I have tried re entering my login both via ginlong and soliscloud, neither work. 
I deactivated my API, reactivated and tried soliscloud access again, still will not let me setup the integration 

**Versions**
HA Version an deployment-2023.4.6
HACS version-1.32.1
Integration version-3.3.3

**Screenshots**
![image](https://github.com/hultenvp/solis-sensor/assets/53425475/407d4071-e53d-4c09-9b7a-69956a4e7f8e)

Thanks,
David

**Comment by hultenvp** [comment]
Ginlong is eond of service and won't work anymore. 
For Soliscloud: please provide debug log, so I can have a look.

**Comment by usbrit** [comment]
Fixed!
Signed in again today, all good. Sorry to have troubled you

**Comment by MichalKurzewski** [comment]
so my issue was i blindly copied https://www.soliscloud.com:13333/ from api key retrieval where it should be https://www.soliscloud.com:13333 <- without the slash.

**Comment by hultenvp** [comment]
Thanks for the update, closing
