### ISSUE TITLE
Incorrect URL for API access request ticket

### ISSUE THREAD

**Issue by EdHargin** [hultenvp/solis-sensor#347]
The first step in the README is "Submit a [service ticket](https://solis-service.solisinverters.com/support/solutions/articles/44002212561-api-access-soliscloud) and wait till it is resolved.".

It appears that URL has changed to something like the one below. (this may vary based on language, but for English at least this seems to be the new correct URL).
https://solis-service.solisinverters.com/en/support/tickets/new

**Comment by hultenvp** [comment]
The link is still correct and explains what to do to request access via a ticket.
Your link directly points to the ticket form, but that would leave people without the manual.
