### ISSUE TITLE
state class total_increasing

### ISSUE THREAD

**Issue by wojcior1** [hultenvp/solis-sensor#35]
I have such warnings in my log:
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:314
Integration: Sensor (documentation, issues)
First occurred: 12:10:10 (3 occurrences)
Last logged: 15:55:10

Entity sensor.solar_energy_this_year from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 4718.51 with last_updated set to 2021-11-29T11:05:56.615843+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_this_month from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 58.67 with last_updated set to 2021-11-29T14:34:51.179783+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_today from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 0.13 with last_updated set to 2021-11-29T14:53:07.995313+00:00. Please report it to the custom component author.

**Comment by hultenvp** [comment]
Hi @wojcior1 ,

Can you share your home assistant version. I think you are on an old one.

Cheers

**Comment by wojcior1** [comment]
Hi,
First of all thank you for your amazing work

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4985
Installed Version | 1.18.0
Stage | running
Available Repositories | 911
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 30.8 GB
disk_used | 20.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Terminal & SSH (9.2.1), Mosquitto broker (6.0.1), Paradox IP150 MQTT Adapter (1.1), Home Assistant Google Drive Backup (0.105.2), File editor (5.3.3), Duck DNS (1.14.0), WireGuard (0.6.0), Check Home Assistant configuration (3.9.0), eWeLink Smart Home (1.2.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by hultenvp** [comment]
Odd, did the arnig show up only those 3 times or does it continue to happen?

**Comment by wojcior1** [comment]
So far it has not happened again.

**Comment by wojcior1** [comment]
It just showed up again:
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:314
Integration: Sensor (documentation, issues)
First occurred: 14:55:10 (3 occurrences)
Last logged: 15:00:10

Entity sensor.solar_energy_today from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 0.24 with last_updated set to 2021-12-01T13:53:33.747814+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_this_month from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 0.24 with last_updated set to 2021-12-01T13:55:35.414982+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_this_year from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 4719.1 with last_updated set to 2021-12-01T13:55:35.415292+00:00. Please report it to the custom component author.

**Comment by hultenvp** [comment]
Hi @wojcior1 

Could you share the history of the 3 sensors from approx. 5 mins before to 5 mins after the event?

Thanks

**Comment by wojcior1** [comment]
Something is wrong here, it looks like the problem is with the data on m.ginlong.com?
![2021-12-02 (1)](https://user-images.githubusercontent.com/91216565/144413065-467c4df3-7ed6-406d-9fbd-0817edbde95f.png)
![2021-12-02 (2)](https://user-images.githubusercontent.com/91216565/144413069-bf1a03d1-2af4-4514-8e75-d20b2945325b.png)
![2021-12-02 (4)](https://user-images.githubusercontent.com/91216565/144413070-2e189db4-8b08-4fb9-8cba-622246c2d1b4.png)
![2021-12-02 (5)](https://user-images.githubusercontent.com/91216565/144413072-69561fb6-8878-4990-bf64-b7a4e570f4be.png)

**Comment by hultenvp** [comment]
My polish(?) is not that good, but it's mentions effective energy?
Could it be that you have a hybrid inverter with battery? Maybe the Solis portal then shows net energy produced or so.
On my portal it says daily energy (active). I have no hybrid system.

**Comment by hultenvp** [comment]
Forgot to add: when you look through daily energy for the past weeks, do you see it happening all the time or just so now and then.
I'm trying to build a picture if we're looking at a feature here or a bug in the data processing

**Comment by hultenvp** [comment]
Hi @wojcior1 , any updates?

**Comment by wojcior1** [comment]
Hi, still the same

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:319
Integration: Sensor (documentation, issues)
First occurred: 17 grudnia 2021, 16:05:10 (3 occurrences)
Last logged: 17 grudnia 2021, 16:05:10

Entity sensor.solar_energy_today from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 1.48 with last_updated set to 2021-12-17T15:01:22.549974+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_this_month from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 17.06 with last_updated set to 2021-12-17T15:03:26.199136+00:00. Please report it to the custom component author.
Entity sensor.solar_energy_this_year from integration solis has state class total_increasing, but its state is not strictly increasing. Triggered by state 4735.89 with last_updated set to 2021-12-17T15:03:26.199498+00:00. Please report it to the custom component author.

**Comment by hultenvp** [comment]
Hi @wojcior1 , thanks for getting back. Could you have a look at my questions? I'd like to help you with this one, but I need to understand what's going on here.

Thanks,
Peter

**Comment by hultenvp** [comment]
Stale ticket, closing.

Feel free to reopen when still an issue on v1.0.0 or higher
