### ISSUE TITLE
Issue with sensor.solis_daily_on_grid_energy.

### ISSUE THREAD

**Issue by ccj2740** [hultenvp/solis-sensor#353]
Anyone else be having issues with the :
sensor.solis_daily_on_grid_energy

An example: Today it is showing 100.9 kWh to grid , but it should only be 10.9 kWh to grid.
![image](https://github.com/hultenvp/solis-sensor/assets/126421743/1ddf76b6-2cc4-4189-b7c7-ba4f82d39e79)

I am pretty sure that this was showing correct 2-3 weeks ago, so wonder why it changed for me and if i can change the . from "100.9 to 10.9" ?

**Comment by hultenvp** [comment]
@ccj2740 please check your workarounds.yaml in ```custom_components/solis```
Set ```correct_daily_on_grid_energy_enabled: false``` to let the integration stop correcting for an API bug.
Let me know if this fixes it as the correction is by default switched off, so if you didn't change anything then it also shouldn't correct.

**Comment by ccj2740** [comment]
@hultenvp I upgraded to 3.5.2 and it solved the problem.
 Thank you so much!!!...
