### ISSUE TITLE
Remaining Battery Capacity stays at 100

### ISSUE THREAD

**Issue by jeroenbal** [hultenvp/solis-sensor#361]
Since 3.5.2, the remaining battery capacity stays at 100%

sensor.my_solis_inverter_remaining_battery_capacity

**Comment by edbanger** [comment]
I have the same issue, but this doesn't seem related to solis-sensor:
- Issues started after scheduled Soliscloud maintenance at 05:00 UTC on 26/03/2023.
- Issue exists in Soliscloud as well
- BMS and Inverter correctly report actual SOC

I've logged a ticket with Solis: https://solis-service.solisinverters.com/en/support/home

**Comment by jeroenbal** [comment]
Oh, thanks for your info. I upgraded the HA solis-sensor that same day...

**Comment by jeroenbal** [comment]
It looks like they fixed it last night :-)

**Comment by edbanger** [comment]
For me this was fixed overnight in Soliscloud, so the SOC is now correctly reported in solis-sensor as well.
