### ISSUE TITLE
Deprecated alias which will be removed in HA Core 2025.5

### ISSUE THREAD

**Issue by Dino0005** [hultenvp/solis-sensor#369]
Deprecated alias which will be removed in HA Core 2025.5

HA Version 2024.5.0 on Home Assistant Yellow 
HACS Version: None (manual installation of Solis integration) 
Integration version: 3.5.2

Log:
Registratore: homeassistant.helpers.typing
Fonte: helpers/deprecation.py:206
Prima occorrenza: 17:22:44 (2 occorrenze)
Ultima registrazione: 17:22:44

HomeAssistantType was used from solis, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'solis' custom integration
ServiceCallType was used from solis, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'solis' custom integration

<img width="1294" alt="Screenshot 2024-05-03 alle 17 49 49" src="https://github.com/hultenvp/solis-sensor/assets/167996504/233cd7ed-3e20-4a5d-afb5-19df334661b8">

**Comment by Dino0005** [comment]
Since no one responded I tried to correct the `custom_components/solis/__init__.py` file myself...
line 11
`from homeassistant.core import HomeAssistant, ServiceCall`
line 14
`from homeassistant.helpers.typing import ConfigType`
line 37
`async def async_setup(hass: HomeAssistant, config: ConfigType):`

**Comment by pivlersmom** [comment]
> Since no one responded I tried to correct the `custom_components/solis/__init__.py` file myself...and I did it this way line 11 `from homeassistant.core import HomeAssistant, ServiceCall` line 14 `from homeassistant.helpers.typing import ConfigType` line 37 `async def async_setup(hass: HomeAssistant, config: ConfigType):`

Same issue here.
works it for you? In my case not.

**Comment by Dino0005** [comment]
Yes, after Home Assistant restarting I no longer get the deprecated alias warning

**Comment by hultenvp** [comment]
Solved as part of #380
