### ISSUE TITLE
No inverters found

### ISSUE THREAD

**Issue by Dino0005** [hultenvp/solis-sensor#370]
**Describe the bug**
No inverters found

HA Version 2024.5.0 on Home Assistant Yellow
HACS Version: None (manual installation of Solis integration)
Integration version: 3.5.2

Log:
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: custom_components.solis.soliscloud_api
Fonte: custom_components/solis/soliscloud_api.py:239
Integrazione: Solis Inverter (documentazione, problemi)
Prima occorrenza: 17:22:57 (3 occorrenze)
Ultima registrazione: 17:29:43

No inverters found

<img width="489" alt="Screenshot 2024-05-03 alle 17 56 57" src="https://github.com/hultenvp/solis-sensor/assets/167996504/5869b529-27ac-4abd-8653-34f3cf9ec1a1">

**Comment by hultenvp** [comment]
Going through old tickets.

Is this issue still occurring? Please follow the [wiki](https://github.com/hultenvp/solis-sensor/wiki/Soliscloud-issues) to test if the API works for you.

**Comment by Dino0005** [comment]
No, I haven't had this issue again since the day of this report

**Comment by hultenvp** [comment]
Thanks, closing ticket.
