### ISSUE TITLE
sensor.solis_energy_today stopped working (becomes unknown)

### ISSUE THREAD

**Issue by khangwei** [hultenvp/solis-sensor#383]
Starting today (27 August)

sensor.solis_energy_today stopped working. I am not sure why. No value is reported . When I checked my Solis App and tried to tally against the entities on my HA, I realized this value is now reported under sensor.solis_daily_grid_energy_used which sounds wrong to begin with.

I assume nothing in this integration changed, so it must be at Solis API...

Anyone having the same issue as me?

Thank you

**Comment by jmason** [comment]
It's not across all users, at least -- I'm still seeing correct values under solis_energy_today.... odd!

**Comment by hultenvp** [comment]
Same here, still working. 
Please check the logs and see what the test script does
https://github.com/hultenvp/solis-sensor/tree/master/test

**Comment by khangwei** [comment]
thanks for your reply. sorry for the silly question but how do i use the test script?

**Comment by hultenvp** [comment]
The doc says look at the [wiki](https://github.com/hultenvp/solis-sensor/wiki/Soliscloud-issues) ;-)

**Comment by wiikka** [comment]
For me everything worked until this morning, and now integration doesn't work anymore. I haven't made any updates nor restarts between last evening (when everything worked) vs this morning (when stopped to work)

**Comment by CraigCallender** [comment]
Looks like the issue (for me) is that no inverters are found:
![image](https://github.com/user-attachments/assets/78c05052-6ea8-442a-896c-342a0c67ed45)

And it'll be somewhere in here.  I'm taking a look at this function to see what I can find out:
```python
async def fetch_inverter_list(self, plant_id: str) -> dict[str, str]:
"""
Fetch return list of inverters { inverter serial : device_id }
"""

device_ids = {}

params = {
	'stationId': plant_id
}
result = await self._post_data_json('/v1/api/inverterList', params)

if result[SUCCESS] is True:
	result_json: dict = result[CONTENT]
	if result_json['code'] != '0':
		_LOGGER.info("%s responded with error: %s:%s",INVERTER_DETAIL, \
			result_json['code'], result_json['msg'])
		return device_ids
	try:
		for record in result_json['data']['page']['records']:
			serial = record.get('sn')
			device_id = record.get('id')
			device_ids[serial] = device_id
	except TypeError:
		_LOGGER.debug("Response contains unexpected data: %s", result_json)
elif result[STATUS_CODE] == 408:
	now = datetime.now().strftime("%d-%m-%Y %H:%M GMT")
	_LOGGER.warning("Your system time must be set correctly for this integration \
	to work, your time is %s", now)
return device_ids
```

**Comment by CraigCallender** [comment]
Most likely it's a solis_cloud API issue.  Running the test script results in a response from the API on line 67 of (`station_id` and `inverter_sn` have been masked):
```
inverter_detail(station_id= 12345678901234, inverter_sn= 43210987654321):  Failed with: API returned an error: Communication error. Please refresh and try again later, error code: None, response None
```

**Comment by CraigCallender** [comment]
I've logged a ticket with Solis Support.  It's often a struggle to get them to forward it to their cloud team (the support email is more for support setting up Inverters, etc...).  But I'll keep the thread updated.  [Ticket ](https://solis-service.solisinverters.com/en/support/tickets/425868) (not sure you'll be able to see it)

**Comment by hultenvp** [comment]
Thanks @CraigCallender for following up with them. 
What is odd is that it only fails for a subset of people.
I have no problems at all, for example.
It could be anything on their backend, but I suspect one of their server instances is down.

I closed the other ticket (#384 ), but I'll leave this one open for anyone to update on status. But I consider this an API issue and have labeled to not a bug

**Comment by ricardito62** [comment]
Was working for me until this morning (so, while failing for a subset of people, it may be a growing subset…)

**Comment by deligatedgeek** [comment]
Same happened to me this morning.  Have tweeted them, but not sure they care that much

**Comment by conallob** [comment]
Another user who has no data in Home Assistant as of today, 2024-08-29. SolisCloud v4.3.9does indeed work though.


One interesting observation after I installed V3.6.0 of this integration is I got promoted to re-auth to SolisCloud. I'm unable to do so, as my PlantID appears to be in hexadecimal, but the integration form is looking for a numberic ID, in base10

**Comment by strickersuk** [comment]
Definitely a growing subset, me too.

**Comment by hultenvp** [comment]
> Another user who has no data in Home Assistant as of today, 2024-08-29. SolisCloud v4.3.9 does indeed work though.
> 
> One interesting observation after I installed V3.6.0 of this integration is I got promoted to re-auth to SolisCloud. I'm unable to do so, as my PlantID appears to be in hexadecimal, but the integration form is looking for a numberic ID, in base10

Hi Conall, please follow the steps in the installation manual. 
https://github.com/hultenvp/solis-sensor
PlantID is the 19-digit number from the plant detail page on SolisCloud.

Maybe reauth is the way to go for everyone observing issues?

**Comment by strickersuk** [comment]
I tried to reauth but got an error, for clarification this was using the 19 digit number.

**Comment by strickersuk** [comment]
No, tried to reinstall using the existing? Is it worth a service request for a new one?

**Comment by hultenvp** [comment]
Not sure if it said before but the apiManage page now explicitly states only for Organizational leaders:
![image](https://github.com/user-attachments/assets/ff35837c-2465-4d26-a9c4-0117b3f5c2fb)

I sincerely hope they are not in the process of revoking access for end-users

**Comment by hultenvp** [comment]
@strickersuk no service request, I only mean the steps on the apiManage page; pressing the activation button, verification mail etc.

**Comment by hultenvp** [comment]
This part: 
![image](https://github.com/user-attachments/assets/0e308912-4bff-4c27-9259-976a3dc4b574)

**Comment by strickersuk** [comment]
Yes, tried that and used my existing API keys.

**Comment by hultenvp** [comment]
> Yes, tried that and used my existing API keys.

You did not get a new key and secret?

**Comment by strickersuk** [comment]
> > Yes, tried that and used my existing API keys.
> 
> You did not get a new key and secret?

Tried to reauth using the API key and secret and got the same error as OctoStu above.

**Comment by strickersuk** [comment]
It just came back.

**Comment by wiikka** [comment]
Yes, data again visible in HA!

**Comment by hultenvp** [comment]
Somebody at ginlong turned a server off and on again ;-)

**Comment by dpgh947** [comment]
Well that was an hour of messing around collecting debug logs that I needn't have bothered with! :-)

I updated to the new 3.6, and it wouldn't connect. Checked the solis app, that was fine. So I collected some logs, and then fell back to previous version, and that didn't start either. Collected some more logs from that, thinking "what has the new version done to my account?" , then realised looking at history that it hadn't worked at all this morning. Then found this thread just as it started working again. Anyway, installed 3.6 again and all seems good now. Great timing!

**Comment by khangwei** [comment]
> The doc says look at the [wiki](https://github.com/hultenvp/solis-sensor/wiki/Soliscloud-issues) ;-)

thank you for this... tried to follow but am getting this error:

![image](https://github.com/user-attachments/assets/b577b39d-7dfd-4bda-8ff6-18bc05add474)

**Comment by hultenvp** [comment]
Use [pip](https://python.land/virtual-environments/installing-packages-with-pip) to install the requests package.

**Comment by khangwei** [comment]
> Use [pip](https://python.land/virtual-environments/installing-packages-with-pip) to install the requests package.

thank you so much. just tried the test script and all looks OK. 

in verbose mode..

I could find my current generation: "etoday": 18.8, "etoday1": 18.8,

which can be found here : 
![image](https://github.com/user-attachments/assets/772b886d-f58b-49c0-b4d9-cd4a14caa495)

and oddly, the previous entity i used is unknown!
![image](https://github.com/user-attachments/assets/e0bce6df-794c-4fbc-9f77-1267acd86e1a)

**Comment by khangwei** [comment]
just want to report that everything is now back to normal. I have my solis energy today back... i did not change anything.

**Comment by crryp** [comment]
For me this just happend after i did update the solis intergration to the latest version. 

Daily usage = unknown

I read in the comments for some it gets back somehow? Will see if it does for me

The grid usage does show the daily value also mentioned in another comment.

**Comment by crryp** [comment]
It went back the next day! 0:00 it was reset to zero!
