### ISSUE TITLE
POWER_VOLT_AMPERE_REACTIVE deprecated in HA 2024.9.0

### ISSUE THREAD

**Issue by Dino0005** [hultenvp/solis-sensor#387]
POWER_VOLT_AMPERE_REACTIVE is a deprecated constant

HA Version 2024.9.0 on Home Assistant Yellow

Integration version: 3.6.0

  logs:
Registratore: homeassistant.const
Fonte: helpers/deprecation.py:197
Prima occorrenza: 19:25:48 (1 occorrenze)
Ultima registrazione: 19:25:48
POWER_VOLT_AMPERE_REACTIVE was used from solis, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'solis' custom integration

<img width="1369" alt="Screenshot 2024-09-04 alle 19 58 11" src="https://github.com/user-attachments/assets/a9ee6da3-6d71-4ea8-a198-0cffcdb1a930">

const.py needs to be updated

**Comment by hultenvp** [comment]
Thanks Dino, fix is ready. Will wait for a week or 2 as not everyone likes to upgrade to a .0 release.
(introduction of UnitOfReactivePower requires 2024.9.0 or higher)
