### ISSUE TITLE
Integration not loading after updated on 17th Nov 2024

### ISSUE THREAD

**Issue by brian-kehoe** [hultenvp/solis-sensor#397]
**Describe the bug**
This had been working up until yesterday when I updated.

An error message is now displayed on the Repairs dashboard:
Error Message
The integration solis could not be found. This happens when a (custom) integration was removed from Home Assistant, but there are still configurations for this integration. Please use the buttons below to either remove the previous configurations for solis or ignore this.

**Config**
Cannot access this in the integrations page

**Versions**
HA Version an deployment: 
Core 2024.11.1
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.2

HACS version
Integration version: | 2.0.1
Frontend version: | 20240903140523

Integration version
Unknown

**Debug logs**
Adding the debug information did not result in any additional logs being generated. This error and warning is all that is being displayed in the logs relating to 'solis'

Setup failed for 'solis': Integration not found  
Failed to load integration for translation: Integration 'solis' not found

Add to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.solis: debug
```
And attach the resulting log to the issue. If yo do not know where to find logs you missed an important step in the install of HACS. ;-)

**Screenshots**

![image](https://github.com/user-attachments/assets/7ca4e97b-ba03-4fac-9b80-fd9a6a866474)

![image](https://github.com/user-attachments/assets/661c89fe-eeb4-4f05-9c03-d23678331fe6)

![image](https://github.com/user-attachments/assets/df16a6db-e7b8-4b0d-896d-99e90baccbe3)

![image](https://github.com/user-attachments/assets/a8eca905-5676-4b16-9a04-bce48b241ac3)

![image](https://github.com/user-attachments/assets/7eb73c7e-cad7-437a-8a63-0b9e14b0214b)

**Comment by hultenvp** [comment]
Use the redownload option in HACS and see if that fixes it.
You can also manually download the translation.py from here and add it to the right folder under custom_components

**Comment by brian-kehoe** [comment]
Thank you, that fixed it for me.

**Comment by brian-kehoe** [comment]
Thank you, that fixed it for me.
