### ISSUE TITLE
Unable to install package aiofiles>=23.1.0,<24.0.0

### ISSUE THREAD

**Issue by benv666** [hultenvp/solis-sensor#399]
**Describe the bug**
After updating to the latest homeassistant beta docker a few days ago, the solis integration refused to load.

**Versions**
HA Version an deployment: 2024.12.0b5
HACS version: 2.0.1
Integration version: 3.7.1

**logs**
```
2024-12-04 13:14:28.847 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package aiofiles>=23.1.0,<24.0.0: × No solution found when resolving dependencies:
  ╰─▶ Because you require aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we
      can conclude that your requirements are unsatisfiable.
2024-12-04 13:14:28.847 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].
```

Not sure where the `aiofiles>=24.1.0` requirement comes from, but this wasn't the case before upgrading and everything worked fine, so possibly just home assistant itself.

**Comment by soheiladeli** [comment]
I have the same issue on new HAS OS core upgrade to latest version 2024.12.0

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 11:34:21 AM (3 occurrences)
Last logged: 11:34:26 AM

Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].

**Comment by eddysteurs** [comment]
also have the error after ha upgrade to 2024.12, reverted back to 2024.11.3 then is working again, willl wait integration update

**Comment by sunnyiiii** [comment]
I have the same issue after upgraded to 2024.12

![image](https://github.com/user-attachments/assets/58a01996-e1af-4909-a8d0-5765c1ecbf45)

**Comment by VyckaLTU** [comment]
Same issue here.

**Comment by funks81** [comment]
Yep - same issue here after upgrading HA Core.

**Comment by ColinSainsbury** [comment]
+

**Comment by benoit-destexhe** [comment]
+1
Same issue here.

**Comment by ep1p** [comment]
Latest alpine linux 3.21 has py3-aiofiles-24.1.0-r0.apk so maybe thats where its coming from if HA has installed that version, but solis has requirement to be <24.0.0

**Comment by patduckless** [comment]
Home assistant core has a merged change to require aiofiles to be v24.1.0.

**Comment by chmutoff** [comment]
There is already a PR waiting to be merged with the fix

**Comment by jparnellx** [comment]
> The issue is within this file - but I am not sure who can update it and push it out !!
> 
> https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/manifest.json

I don't understand how to update through github and the affect of doing so, so for the moment i have manually changed the manifest.json within my HA install to allow <25 e.g. aiofiles>=23.1.0,<25.0.0

**Comment by mwitlox** [comment]
> > The issue is within this file - but I am not sure who can update it and push it out !!
> > https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/manifest.json
> 
> I don't understand how to update through github and the affect of doing so, so for the moment i have manually changed the manifest.json within my HA install to allow <25 e.g. aiofiles>=23.1.0,<25.0.0

I can confirm that this indeed works. Easy quick fix for now.

**Comment by bbartje** [comment]
It works after manual text edit indeed. Thanks.
