### ISSUE TITLE
Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].

### ISSUE THREAD

**Issue by jojkopeter** [hultenvp/solis-sensor#401]
**Describe the bug**

**Config**
Your anonymized config entry

**Versions**
HA Version an deployment
HACS version
Integration version

Error after update Home Assistant 

Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].

**Comment by MiguelCosta** [comment]
Duplicate: https://github.com/hultenvp/solis-sensor/issues/399

**Comment by IM35461** [comment]
I am getting the same after updating my system.

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 08:40:19 (1 occurrences)
Last logged: 08:40:19

Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].

**Comment by terppatyyppi** [comment]
Yes, same here. Broke after 2024.12 update. Looking forward to some wonderful people creating a fix!

**Comment by trevore40** [comment]
I have the same issue too after the latest update.
Please fix it as soon as you can.
Thank you!

**Comment by los-cuentos** [comment]
Same issue

**Comment by ColinSainsbury** [comment]
If you open \custom_components\solis\manifest.json with Studio Code Server or the Text File Editor and change line 12 to read     "aiofiles>=23.1.0,<25.0.0" (in the broken version it reads     "aiofiles>=23.1.0,<24.0.0") and reboot HA it will work.

The latest version of HA upgraded to the latest version of Python which includes version 24.1.0 of aiofiles which was outside of the range specified thereby breaking the integration.

**Comment by trevore40** [comment]
Thanks Colin, I will try it later

**Comment by IM35461** [comment]
> If you open \custom_components\solis\manifest.json with Studio Code Server or the Text File Editor and change line 12 to read `"aiofiles>=23.1.0,<25.0.0" ` (in the broken version it reads `"aiofiles>=23.1.0,<24.0.0"`) Reboot HA it will work.
> 
> The latest version of HA upgraded to the latest version of Python which includes version 24.1.0 of aiofiles which was outside of the range specified thereby breaking the integration.

Colin,
Many thanks that did the trick :)

![Screenshot 2024-12-05 172219](https://github.com/user-attachments/assets/28720943-1f5e-4606-a7b5-c6ec0880bb6d)

**Comment by hultenvp** [comment]
Fixed, by pr #400 
Release 3.7.2
