### ISSUE TITLE
Solis not working after latest update to HA

### ISSUE THREAD

**Issue by canc3r1** [hultenvp/solis-sensor#404]
After the latest update, Solis has stopped responding. The below is the log entry. 

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 16:08:38 (1 occurrences)
Last logged: 16:08:38

Setup failed for custom integration 'solis': Requirements for solis not found: ['aiofiles>=23.1.0,<24.0.0'].

These are my versions.

Core
2024.12.0
Supervisor
2024.11.4
Operating System
14.0

I'm non technical so let me know if you need any other thing and ill get it.

**Comment by hultenvp** [comment]
Already fixed, please update to 3.7.2
