### ISSUE TITLE
V3.8.0 Battery sensor

### ISSUE THREAD

**Issue by jtessens** [hultenvp/solis-sensor#408]
Is it possible that the yearly charged discharged has the wrong formatting?
While daily and monthly is correct the yearly shows in my case 2.306 kWh where I expect to see 2,306 kWh or 2.306 MWh.
![solis380](https://github.com/user-attachments/assets/6ccbb54e-1938-4e22-9742-932200479265)

**Comment by hultenvp** [comment]
@jtessens: should be fixed now. Please reopen and run the example app from the repo if the issue still occurs. See https://github.com/hultenvp/solis-sensor/wiki/Soliscloud-issues
