### ISSUE TITLE
Daily incorrect reading energy today

### ISSUE THREAD

**Issue by peterdusink** [hultenvp/solis-sensor#43]
Hi,

Almost daily there's an incorrect reading from sensor.my_solis_inverter_energy_today. It looks like the production of previous day is shown between 07 and 08 am.
![image](https://user-images.githubusercontent.com/85815182/146586942-06768cb2-3a2e-4a06-ad06-cd9829613f5f.png)

Not sure why this happens and how to fix.

The energy dashboard picks up this reading and is unusable now:-(

Actual production today is 0.2 KWH

![image](https://user-images.githubusercontent.com/85815182/146587639-09a5fefd-a086-43a3-85ff-c4fa97c53035.png)

Energy dashboard shows 

![image](https://user-images.githubusercontent.com/85815182/146587706-8f3b5322-e7ee-46ed-bc1e-3d02647be67c.png)

**Comment by hultenvp** [comment]
Hi @peterdusink,

There is a fix in the code that resets the energy today at midnight. Without this fix it would happen at sunrise and that would skew daily figures. 
My guess is that for some reason the value reverts until the values of the new day come in. 
I'll need more days to figure out what triggers the reversal.

Could you share with me the exact values before reset and at the red arrow?

Thanks

**Comment by peterdusink** [comment]
Hi @hultenvp,

Thank you for the reply. 

The values before reset and red arrow are the same. 

But I think to know what triggers the reversal. 

I have been editing dashboards and configuration in the last days. It seem to only happen when I'm editing configuration.yaml and performing some restarts to apply the updated configuration.yaml

I didn't see value reverting by restart HA only (without modified configuration.yaml)

Today I did not make any changes, or restart. Now the solar readings are correct :-)

Thanks.

**Comment by hultenvp** [comment]
Ah, that indeed will cause the integration to revert.
Looks like you need to postpone your work on HomeAssistant to later on the day in winter time ;-)

Thanks for getting back, closing issue.
