### ISSUE TITLE
HA core_2021.12.4 HTTP_OK Configuration Validation error

### ISSUE THREAD

**Issue by Caleroific** [hultenvp/solis-sensor#44]
After upgrading to HA Release core_2021.12.4 all solis entities are unavailable. I cannot reboot HA. Server Controls/Configuration validation indicates 'Configuration invalid' with the folllowing message:
Platform error sensor.solis - cannot import name 'HTTP_OK' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py

Any idea why this should be?

Thank you

**Comment by Caleroific** [comment]
Apologies. I have resolved this by loading latest version of solis-sensor 0.4.1. 

Problem resolved.

**Comment by hultenvp** [comment]
Closing ;-)
