### ISSUE TITLE
V1.0.0 not robust enough in avoiding energy today reporting yesterday's energy.

### ISSUE THREAD

**Issue by hultenvp** [hultenvp/solis-sensor#54]
Still seeing spikes at startup, messing up energy dashboard.
Looks like energy today is not always reset already when state transitions to 'ON'.

Add grace period of ~10 minutes after inverter switching on before accepting 'energy today' values.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/61835400/150635513-62989c8f-bda6-4cdb-ba97-a4a5fedb57e5.png">

**Comment by henrikeri** [comment]
@hultenvp 
Not sure if the grace period is long enough, I had yesterdays energy populate this morning. Should we re-open? 
![image](https://user-images.githubusercontent.com/35510093/151516979-cf185ee5-9075-44f0-ad51-14bf9d3b521c.png)

**Comment by hultenvp** [comment]
The grace period is not the problem. The problem is that the dir method sorts the list of attributes I return. Apparently that's acoording to spec, but it means 'energy_today' gets evaluated before 'status' and thus my check has no value as the timestamp is wrong. 
I'm testing an update, it worked nice this morning.  Plan to make a new release when also the temperature issue gets a conclusion.

Reopening this issue to get it included in release notes
<img width="928" alt="image" src="https://user-images.githubusercontent.com/61835400/151522475-991d18e6-71ec-4a55-86a3-ca2fd41c7dd8.png">
