### ISSUE TITLE
FR: Inverter as a device ?

### ISSUE THREAD

**Issue by LucidityCrash** [hultenvp/solis-sensor#64]
Would it be possible to make it so that each inverter shows up as a device with a number of sensor entities associated with it rather than just the sensor entities by themselves ?

**Comment by hultenvp** [comment]
https://developers.home-assistant.io/docs/device_registry_index/

Looks like a good one. I'll have a look, but will have to wait a bit I'm afraid. Bit busy.

**Comment by hultenvp** [comment]
Hey @LucidityCrash 

I couldn't resist taking a look at the device registry thing.
Looks like a pretty straightforward thing to implement.

We could keep it simple and inly introduce device "inverter" or we could go with a bit more elaborate device structure and use the via_device:

```
inverter -+--- battery
          |--- string1
          |--- string2
          |--- ...
          |--- stringx

```

It would give some structure to all sensors. Battery definitely makes sense in my view, string devices could be a nice way to cluster all DC sensors. Phase is a bit difficult to see as a separate device, would just have that under inverter, same with grid.

What do you think?

**Comment by LucidityCrash** [comment]
hmmm interesting ... I was originally just thinking of just a single device (inverter) that all the sensors would be listed under so you can see related sensors etc.  The idea of breaking those into groups is interesting but does it really gain you anything  over just having everything under inverter ?

**Comment by hultenvp** [comment]
For the battery I see the value. It's an optional and separate part only present in hybrid systems. For the strings I admit it's debatable. Battery device and related sensors would look a bit like this screenshot, but then "connected via inverter X"

![Screenshot_20220126-185219](https://user-images.githubusercontent.com/61835400/151219586-5b02822e-8623-43cf-837a-892762827f7a.png)

Apart from the device overview under configuration I see no usage of the device registry. Perhaps there are custom cards, but for now it looks like a feature that is not used to it's potential.

**Comment by hultenvp** [comment]
Look s like I first need to implement the config flow:
https://community.home-assistant.io/t/how-to-add-devices-to-device-registry/160537/3

**Comment by Dduck112** [comment]
Hello sir,
I just started with HA and own a Growatt and a solis inverter.
For your info ill show you the growatt setup:
Its an intergration with a fiew devises and sensors. My setup is in dutch.


the integration taile: 
![image](https://user-images.githubusercontent.com/48312805/165746849-ddbbb1e6-68da-4043-bb38-672c0e60f074.png)
the devices: 
![image](https://user-images.githubusercontent.com/48312805/165746894-f7843fd1-f1da-4a52-9964-3fbb6acabcc1.png)
the sensors for dev1:
![image](https://user-images.githubusercontent.com/48312805/165746807-33cd6d22-b7c7-465b-a421-a89b0c8f8722.png)
the sensors for dev 2:
![image](https://user-images.githubusercontent.com/48312805/165746989-55fe618a-f021-46d0-b3c6-a8340504318e.png)

**Comment by hultenvp** [comment]
Done.
Device registry only works for integrations with a config entry (=config flow).
Config flow and device now added.
