### ISSUE TITLE
*inverter_ac_output_total_power reports kW as W

### ISSUE THREAD

**Issue by suneworld** [hultenvp/solis-sensor#68]
Hi! 
After the last update the AC Output Total Power reports the Watts as Kilo Watts.

![image](https://user-images.githubusercontent.com/74769325/151351069-65dbaf05-bdb7-482b-b179-15b2d937ab20.png)
![image](https://user-images.githubusercontent.com/74769325/151351104-6359bc40-b1f2-46de-8edf-0cfbedc6140f.png)

My workaround locally is to create a sensor that multiplies the value with 1000 - but maybe this should be fixed in the next release?

`- platform: template
  sensors:
    power_production_now:
      icon_template: "hass:flash"
      unit_of_measurement: "kW"
      value_template: >-
        {{ (states('sensor.my_solis_inverter_ac_output_total_power')|float(0)*1000)|round(0)}}
`

**Comment by LucidityCrash** [comment]
See issue #56 😁

**Comment by suneworld** [comment]
Yes, duplicate. Closing.
