### ISSUE TITLE
no version key

### ISSUE THREAD

**Issue by jahpster** [hultenvp/solis-sensor#7]
No 'version' key in the manifest file for custom integration 'solis'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'solis'

**Comment by hultenvp** [comment]
Hi @jahpster: The manifest file has a version key since about 4 months. Please update to latest version of the Solis repository

**Comment by jahpster** [comment]
Hi

Thanks for the response and your work!
I thought I updated but clearly not.



Op ma 28 jun. 2021 13:59 schreef hultenvp ***@***.***>:

**Comment by hultenvp** [comment]
No problem, happens to the best. Thanks for confirming. Closing this issue.
