### ISSUE TITLE
2.0.1 - Energy from Yesterday reported

### ISSUE THREAD

**Issue by henrikeri** [hultenvp/solis-sensor#76]
**Describe the bug**
2.0.1 Still reports energy from yesterday. However, today only energy from 1 repeater was reported if this is of any help.

**Config**
sensor:
  - platform: solis
    name: "Inverter"
    portal_domain: "m.ginlong.com"
    portal_username: !secret solisUser
    portal_password: !secret solisPass
    portal_plant_id: !secret solisPlant

**Versions**
HA Version: core-2022.2.0b3, Home Assistant OS 7.2
HACS 1.20.0
Solis 2.0.1

**Debug logs**
No log issue reflects what is happening.
 
**Screenshots**
![bug](https://user-images.githubusercontent.com/35510093/151693925-17b54631-0c09-40e0-b77b-4855d254d555.png)

**Comment by hultenvp** [comment]
Hmmm, this is....interesting. The fix works on my inverter, but apparently still some corner case I overlooked. More leads are welcome so that I can try to reproduce.

**Comment by Siwek666** [comment]
Works perfect for me i think with solarman platform integration.. Thanks so much.

Versions
HA Version: core-2021.12.10, Home Assistant OS 7.2
HACS 1.20.0
Solis 2.0.1

<img width="931" alt="Zrzut ekranu 2022-01-30 o 11 16 47" src="https://user-images.githubusercontent.com/98656176/151697412-b5719e34-f0ad-42c9-b816-c83581b78364.png">

**Comment by hultenvp** [comment]
Ugghhh, I think I found it. Line 153 in service.py contains a wrong test; '<' should have been '>'. As a result the test evaluates wrong and returns for one measurement still the energy of yesterday. No clue why the problem went away with me and you still see it.
Running tests now.

**Comment by henrikeri** [comment]
I have changed the line as well. Will report results tomorrow around noon when it is up and running. It also only seems to get 1 of the DC lines PV1, not PV2 of my multi string inverter. Is this related to the same?

**Comment by hultenvp** [comment]
Thanks looking forward to the result. I tested it, looks to be okay now, but I want to see if it doesn't break anything unexpected tomorrow when the sun comes up 

Your other issue seems unrelated. Could you let a debug log and create a new issue for that?

Cheers

**Comment by henrikeri** [comment]
@hultenvp, the change seems to work at my end as well. It showed up as intended after sunrise this morning. As for the issue with PV2, it is once more showing.....

**Comment by hultenvp** [comment]
Thanks for letting me know this fix works, please open an issue for the PV2, but please add debug logging as I'm only having one string here.

**Comment by hultenvp** [comment]
Released in v2.0.2. Let's pray it is now really fixed

**Comment by cpuks** [comment]
Just had this issue again on 2.0.6 - whole yesterday production added to todays morning.

![solar](https://user-images.githubusercontent.com/21194723/152685829-8e01af76-cab5-4d36-9711-fe5c0eaee0f0.png)

**Comment by kazikskrz** [comment]
I'm having the same here. Every few days I get production value from day before.
version 2.1.0
HA 2022.3.5
![2022-03-28_08h35_43](https://user-images.githubusercontent.com/54333498/160342115-03e4f6e6-674a-4d86-b78d-68f791d445a0.png)
![2022-03-28_08h34_44](https://user-images.githubusercontent.com/54333498/160342133-40c464e7-2024-4614-a6f0-93343d064856.png)
![2022-03-28_08h33_35](https://user-images.githubusercontent.com/54333498/160342142-de9c1b74-67c3-4031-b1a7-06ab49261d2f.png)
