### ISSUE TITLE
power-wheel-card

### ISSUE THREAD

**Issue by jasonmadigan** [hultenvp/solis-sensor#89]
Not a bug, just wondered if anyone had used these sensors with https://github.com/gurbyz/power-wheel-card? Was curious if anyone had a config to share as an example (haven't quite been able to get the arrows to work as I expect they should yet).

**Comment by henrikeri** [comment]
@jasonmadigan 

It works perfectly for me so far (tested it when I saw this bug report). I am using the following YAML configuration for the card:

`type: custom:power-wheel-card`
`title_power: Power distribution`
`title_energy: Energy distribution`
`title_money: Energy costs/savings`
`solar_power_entity: sensor.solis_totaleffekt` (in W)
`grid_power_consumption_entity: sensor.power` (in W)
`grid_power_production_entity: sensor.power_production` (in W)
`production_is_positive: true`
`solar_energy_entity: sensor.solis_today_production`
`grid_energy_consumption_entity: sensor.accumulated_consumption`  (in kWh)
`grid_energy_production_entity: sensor.accumulated_production` (in kWh)
`energy_consumption_rate: 2`
`energy_production_rate: 1.75`
`money_unit: NOK`
`solar_icon: mdi:white-balance-sunny`
`grid_icon: mdi:flash`
`home_icon: mdi:home-assistant`
`power_decimals: 2`
`energy_decimals: 2`
`money_decimals: 0`
`color_icons: true`
`consuming_color: '#33ff33'`
`producing_color: '#dd5500'`
`invert_grid_colors: false`
`active_arrow_color: '#FF9800'`
`initial_view: energy`
`initial_auto_toggle_view: true`
`auto_toggle_view_period: 5`
`

**Comment by jasonmadigan** [comment]
thank you @henrikeri! given your sensors are probably custom/renamed, I was wondering (hoping, really) if you could point us at what sensors are what in terms of what's coming from the integration. I'm not sure what these sensors map to, for example: `sensor.solis_totaleffek`, `sensor.accumulated_consumption`

**Comment by henrikeri** [comment]
Sure @jasonmadigan:

I have three inverteres so:
- sensor.solis_totaleffekt  is a mapping of 3 separate "sensor.inverter_ac_output_total_power" from the integration
- sensor.solis_today_production is a mapping of 3 separate "sensor.inverter_energy_today" from the integration

As for the remaining:
- sensor.power_production, sensor.power, sensor.accumulated_consumption and sensor.accumulated_production are from the Tibber integration

Hope this helps?

**Comment by jasonmadigan** [comment]
that helps a bit thanks again @henrikeri - I suppose I was looking for some "all in one" config, using just the Solis sensors, using the grid CTs

**Comment by hultenvp** [comment]
Closing stale issue, please open discussion if you'd like to discuss further
